name: Stats

on: 
  push: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Script
        run: python ${GITHUB_WORKSPACE}/stats.py

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated commit from GitHub Actions"
          branch: main
